### ISSUE TITLE
Bottleneck 

### ISSUE THREAD

**Issue by shahzebsiddiqui** [shahzebsiddiqui/Python-buildtest-config#13]

**Comment by shahzebsiddiqui** [comment]
https://pypi.python.org/pypi/Bottleneck/
http://berkeleyanalytics.com/bottleneck/
https://github.com/kwgoodman/bottleneck/tree/master/bottleneck/tests

**Comment by singh-vijay** [comment]
https://github.com/shahzebsiddiqui/Python-buildtest-config/commit/89ae6bc25afb71e69a87dd48251e0d13cfb7bad1
