### ISSUE TITLE
cdecimal 

### ISSUE THREAD

**Issue by shahzebsiddiqui** [shahzebsiddiqui/Python-buildtest-config#14]

**Comment by shahzebsiddiqui** [comment]
http://www.bytereef.org/mpdecimal/doc/cdecimal/
https://docs.python.org/3/library/decimal.html

**Comment by singh-vijay** [comment]
https://github.com/shahzebsiddiqui/Python-buildtest-config/commit/1fc3ce880e18c6359c7e1ec5e62286cf2f2d8053
