### ISSUE TITLE
bitarray 

### ISSUE THREAD

**Issue by shahzebsiddiqui** [shahzebsiddiqui/Python-buildtest-config#9]

**Comment by shahzebsiddiqui** [comment]
https://pypi.python.org/pypi/bitarray/
https://github.com/ilanschnell/bitarray/tree/master/examples

**Comment by singh-vijay** [comment]
https://github.com/shahzebsiddiqui/Python-buildtest-config/commit/a38608bf1f5debfcea0b0536d380da186cda6b6c
